print("1. ",int(3.0)) # Funkcja "int()" zmienia liczbę zmiennoprzecinkową (float) na liczbę całkowitą (int)
print("2. ",float(3)) # Funkcja "float()" zmienia liczbę całkowitą (int) na liczbę zmiennoprzecinkową (float)
print("3. ",float("3.0")) # Funkcja "float()" zamienia napis (string), który ma w sobie liczbę, na liczbę zmiennoprzecinkową (float)
print("4. ",str(12.4)) # Funkcja "str()" zamienia liczbę (w tym przypadku zmiennoprzecinkową) na ciąg znaków/tekst (string)
print("5. ",bool(0)) # Funkcja "bool()" to logiczny typ danych, przyjmuje tylko dwie wartości (true/false) - wartość 0 to fałsz (false) a każda inna to prawda (true)